# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_core import user_pb2 as user__pb2


class UserStub(object):
    """User
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/jijidown.core.User/Info',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=user__pb2.UserInfoReply.FromString,
                )
        self.LoginQRCode = channel.unary_unary(
                '/jijidown.core.User/LoginQRCode',
                request_serializer=user__pb2.UserLoginQRCodeReq.SerializeToString,
                response_deserializer=user__pb2.UserLoginQRCodeReply.FromString,
                )
        self.LoginStatus = channel.unary_stream(
                '/jijidown.core.User/LoginStatus',
                request_serializer=user__pb2.UserLoginStatusReq.SerializeToString,
                response_deserializer=user__pb2.UserLoginStatusReply.FromString,
                )
        self.ImportCookie = channel.unary_unary(
                '/jijidown.core.User/ImportCookie',
                request_serializer=user__pb2.UserImportCookieReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class UserServicer(object):
    """User
    """

    def Info(self, request, context):
        """获取用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginQRCode(self, request, context):
        """获取登录二维码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginStatus(self, request, context):
        """获取登录状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportCookie(self, request, context):
        """导入 Cookie
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=user__pb2.UserInfoReply.SerializeToString,
            ),
            'LoginQRCode': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginQRCode,
                    request_deserializer=user__pb2.UserLoginQRCodeReq.FromString,
                    response_serializer=user__pb2.UserLoginQRCodeReply.SerializeToString,
            ),
            'LoginStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.LoginStatus,
                    request_deserializer=user__pb2.UserLoginStatusReq.FromString,
                    response_serializer=user__pb2.UserLoginStatusReply.SerializeToString,
            ),
            'ImportCookie': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportCookie,
                    request_deserializer=user__pb2.UserImportCookieReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jijidown.core.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """User
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jijidown.core.User/Info',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            user__pb2.UserInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginQRCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jijidown.core.User/LoginQRCode',
            user__pb2.UserLoginQRCodeReq.SerializeToString,
            user__pb2.UserLoginQRCodeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/jijidown.core.User/LoginStatus',
            user__pb2.UserLoginStatusReq.SerializeToString,
            user__pb2.UserLoginStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportCookie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/jijidown.core.User/ImportCookie',
            user__pb2.UserImportCookieReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
