# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskstatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10taskstatus.proto\x12\rjijidown.core*\xcb\x01\n\x0eTaskStatusType\x12\x1b\n\x17TaskStatusType_TASK_ALL\x10\x00\x12\x1d\n\x19TaskStatusType_TASK_ERROR\x10\x01\x12\x1c\n\x18TaskStatusType_TASK_STOP\x10\x02\x12\x1c\n\x18TaskStatusType_TASK_WAIT\x10\x03\x12\x1f\n\x1bTaskStatusType_TASK_RUNNING\x10\x04\x12 \n\x1cTaskStatusType_TASK_COMPLETE\x10\x05\x42\x62ZFgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/taskstatuspb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskstatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/taskstatuspb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_TASKSTATUSTYPE']._serialized_start=36
  _globals['_TASKSTATUSTYPE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
