# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/blinkresult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16type/blinkresult.proto\x12\rjijidown.core\"9\n\x0b\x42LinkResult\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04mark\x18\x02 \x01(\t\x12\x10\n\x08web_link\x18\x03 \x01(\tBcZGgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/blinkresultpb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type.blinkresult_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZGgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/blinkresultpb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_BLINKRESULT']._serialized_start=41
  _globals['_BLINKRESULT']._serialized_end=98
# @@protoc_insertion_point(module_scope)
