# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etype/api.proto\x12\rjijidown.core*;\n\x07\x41piType\x12\x0f\n\x0b\x41piType_WEB\x10\x00\x12\x0e\n\nApiType_TV\x10\x01\x12\x0f\n\x0b\x41piType_APP\x10\x02\x42[Z?github.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/apipb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z?github.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/apipb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_APITYPE']._serialized_start=33
  _globals['_APITYPE']._serialized_end=92
# @@protoc_insertion_point(module_scope)
