# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/servericon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15type/servericon.proto\x12\rjijidown.core*\xe1\x06\n\x0eServerIconType\x12\x1f\n\x1bServerIconType_ICON_UNKNOWN\x10\x00\x12!\n\x1dServerIconType_ICON_WINDOWS_7\x10\x01\x12\"\n\x1eServerIconType_ICON_WINDOWS_10\x10\x02\x12\"\n\x1eServerIconType_ICON_WINDOWS_11\x10\x03\x12\x1d\n\x19ServerIconType_ICON_LINUX\x10\x04\x12$\n ServerIconType_ICON_LINUX_DEBIAN\x10\x05\x12%\n!ServerIconType_ICON_LINUX_RASPIOS\x10\x06\x12$\n ServerIconType_ICON_LINUX_UBUNTU\x10\x07\x12$\n ServerIconType_ICON_LINUX_FEDORA\x10\x08\x12%\n!ServerIconType_ICON_LINUX_RED_HAT\x10\t\x12$\n ServerIconType_ICON_LINUX_CENTOS\x10\n\x12+\n\'ServerIconType_ICON_LINUX_CENTOS_STREAM\x10\x0b\x12)\n%ServerIconType_ICON_LINUX_ROCKY_LINUX\x10\x0c\x12\'\n#ServerIconType_ICON_LINUX_ALMALINUX\x10\r\x12(\n$ServerIconType_ICON_LINUX_ARCH_LINUX\x10\x0e\x12\x1e\n\x1aServerIconType_ICON_DARWIN\x10\x0f\x12*\n&ServerIconType_ICON_DARWIN_HIGH_SIERRA\x10\x10\x12%\n!ServerIconType_ICON_DARWIN_MOJAVE\x10\x11\x12\'\n#ServerIconType_ICON_DARWIN_CATALINA\x10\x12\x12&\n\"ServerIconType_ICON_DARWIN_BIG_SUR\x10\x13\x12\'\n#ServerIconType_ICON_DARWIN_MONTEREY\x10\x14\x12&\n\"ServerIconType_ICON_DARWIN_VENTURA\x10\x15\x42\x62ZFgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/servericonpb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type.servericon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/servericonpb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_SERVERICONTYPE']._serialized_start=41
  _globals['_SERVERICONTYPE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
