# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/taskdo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11type/taskdo.proto\x12\rjijidown.core*p\n\x06TaskDo\x12\x12\n\x0eTaskDo_NOTHING\x10\x00\x12\x10\n\x0cTaskDo_PAUSE\x10\x01\x12\x11\n\rTaskDo_RESUME\x10\x02\x12\x11\n\rTaskDo_DELETE\x10\x03\x12\x1a\n\x16TaskDo_DELETE_AND_FILE\x10\x04\x42^ZBgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/taskdopb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type.taskdo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZBgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/taskdopb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_TASKDO']._serialized_start=36
  _globals['_TASKDO']._serialized_end=148
# @@protoc_insertion_point(module_scope)
