# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/updatestatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17type/updatestatus.proto\x12\rjijidown.core*T\n\x10UpdateStatusType\x12\x0c\n\x08\x43HECKING\x10\x00\x12\x14\n\x10NOTSUPPORTUPDATE\x10\x01\x12\x0c\n\x08UPTODATE\x10\x02\x12\x0e\n\nNEEDUPDATE\x10\x03\x42\x64ZHgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/updatestatuspb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type.updatestatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/updatestatuspb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_UPDATESTATUSTYPE']._serialized_start=42
  _globals['_UPDATESTATUSTYPE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
