# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10type/video.proto\x12\rjijidown.core*\\\n\tVideoType\x12\x15\n\x11VideoType_UNKNOWN\x10\x00\x12\x11\n\rVideoType_AVC\x10\x01\x12\x12\n\x0eVideoType_HEVC\x10\x02\x12\x11\n\rVideoType_AV1\x10\x03\x42]ZAgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/videopb\xaa\x02\x17JiJiDown.Core.SDK.Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type.video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZAgithub.com/JiJiDown/JiJiDownCore-go/common/jijidown/types/videopb\252\002\027JiJiDown.Core.SDK.Types'
  _globals['_VIDEOTYPE']._serialized_start=35
  _globals['_VIDEOTYPE']._serialized_end=127
# @@protoc_insertion_point(module_scope)
